service: createSchedule

provider:
  name: aws
  runtime: nodejs10.x
  stage: testing
  region: us-west-2

functions:
  app:
    handler: server.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
